### PR TITLE
refactor: rework opportunist to reduce ap cost instead of ap recovery

### PR DESCRIPTION
**Pull request by LordMidas**
- Instead of halving the AP cost of the first 2 throwing attacks in the battle, it now halves the cost of all throwing attacks but only during the first round of battle.
- Instead of recovering 4 AP after stepping on a corpse, it now makes the next throwing attack cost no AP. (Still reduces its Fatigue cost by 50% like before).

The first point is somewhat of a sidegrade as you can now potentially unleash 4 throwing attacks during the first turn if you want if you don't move from your position. But it makes more sense thematically to me as an "opportunistic" playstyle and doesn't suffer from the weird situation we have currently where you are fatigued out after 4 rounds and still have the halved AP cost for the throwing attacks.

The second point reduces the silly chain of corpse hopping that can lead to extremely long turns as you keep recovering Action Points and may have other perks which reduce the cost of your attacks.

### CODE REVIEW

**Comment by Uberbagel** [comment]
> The first point is somewhat of a sidegrade as you can now potentially unleash 4 throwing attacks during the first turn if you want if you don't move from your position. But it makes more sense thematically to me as an "opportunistic" playstyle and doesn't suffer from the weird situation we have currently where you are fatigued out after 4 rounds and still have the halved AP cost for the throwing attacks.

When does this weird situation happen? Only when the player doesn't utilize their 2 free throws and saves them for later?

**Comment by LordMidas** [comment]
Yes. A guy could be attacking in melee but then use throwing attacks 4 rounds later and benefit from "opportunist". Which seems weird.

**Comment by Uberbagel** [comment]
> Yes. A guy could be attacking in melee but then use throwing attacks 4 rounds later and benefit from "opportunist". Which seems weird.

It is a bit weird, but I think chances are small this will actually happen. I think the large majority of players will prefer to get that extra damage out early where it has a greater chance of positively impacting the fight.

I think half AP during the first round is both too restrictive and too strong at the same time. The player will only benefit from it if the enemy charges. Then if they do, that's potentially 4 attacks of value vs. 3 attacks from the current design. The enemy will only benefit from it if they have ranged advantage and the player charges. 

Perhaps a middle ground is half the cost of the first two throws for the first two rounds in combat.

**Comment by LordMidas** [comment]
Yeah let's go with the restriction of first 2 rounds for now.

**Pull request merged**
