### PR TITLE
feat: add new concept 'Zone of Control' and refactor it into many texts

### PR DESCRIPTION
**Pull request by Darxo**
I tried applying it for 'footwork.nut' (vanilla active skill) and 'spearwall_effect.nut' (vanilla effect) but doing so froze my gamer everytime I load a savegame or start a new run without any warnings/errors except "Magic number doesn't match" during loading.

### CODE REVIEW

**Comment by LordMidas** [comment]
Your PR description says that the game is freezing. Is that still the case or is it working properly now?

**Comment by Darxo** [comment]
This version does not freeze the game.

But this version also doesn't include a hyperlink for the vanilla 
- active ability `footwork` description
- passive `spearwall` effect description

**Review by LordMidas — APPROVED** [review]

**Comment by LordMidas** [comment]
Looks good

**Comment by LordMidas** [comment]
I changed the commit message and merged it.

**Pull request merged**
